- name: Install packages
  dnf:
    name: 
      - fish
      - neovim
      - timeshift
      - neofetch 
      - htop 
      - gnome-tweaks
      - gnome-shell-extension-appindicator
      - inkscape
      - snapd 
    state: present

- name: Install programming languagues
  dnf:
    name:
      - go
      - rustc
      - cargo
    state: present

- name: Install Nvidia Driver
  dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - vulkan
    state: present

- name: Create a symlink for snapd
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  
- name: Install Snap packages
  snap:
    name:
      - postman
      - dbeaver-ce
 
- name: Install Snap packages with --classic flag
  snap:
    classic: yes
    name:
      - node
      - code
      - spotify

- name: Install system flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
   - com.slack.Slack
   - org.remmina.Remmina
   - com.discordapp.Discord
   - org.telegram.desktop
